Added further logging and tweaked ordering.

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -70,6 +70,25 @@ stages:
         FIND_BASE_URL: $(findBaseUrl)
 
     - script: |
+        make ci.cucumber
+        test_result=$?
+        if [ "$test_result" == "0" ]
+        then
+          true;
+        else
+          echo "ERROR: Cucumber spec tests failed."
+          false
+        fi
+      displayName: 'Cucumber specs'
+      env:
+        dockerHubUsername: $(dockerHubUsername)
+        dockerHubImageName: $(imageName)
+        RAILS_ENV: test
+        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)
+        AUTHORISED_HOSTS: $(authorisedHosts)
+        FIND_BASE_URL: $(findBaseUrl)
+
+    - script: |
         make ci.test
         test_result=$?
         if [ "$test_result" == "0" ]
@@ -79,23 +98,14 @@ stages:
           echo "ci.test failed"
           if [ -f results/rspec-results.xml ]
           then
+            echo "ERROR: Tests failed. results/rpsec-results.xml output:"
             cat results/rspec-results.xml
           else
-            echo "Unable to read results/rpsec-results.xml. The file was either not created or the copy from the container failed."
+            echo "ERROR: Tests failed. Unable to read results/rpsec-results.xml. The file was either not created or the copy from the container failed."
           fi
           false
         fi
       displayName: 'Execute tests'
-      env:
-        dockerHubUsername: $(dockerHubUsername)
-        dockerHubImageName: $(imageName)
-        RAILS_ENV: test
-        GOVUK_NOTIFY_API_KEY: $(govukNotifyAPIKey)
-        AUTHORISED_HOSTS: $(authorisedHosts)
-        FIND_BASE_URL: $(findBaseUrl)
-
-    - script: make ci.cucumber
-      displayName: 'Cucumber specs'
       env:
         dockerHubUsername: $(dockerHubUsername)
         dockerHubImageName: $(imageName)
