log the rspec seed value in the console output.
It is also available in the test results xml file which is published as
build artifact.

diff --git a/run-rspec-test-template.yml b/run-rspec-test-template.yml
--- a/run-rspec-test-template.yml
+++ b/run-rspec-test-template.yml
@@ -7,29 +7,31 @@ parameters:
 steps:
   - script: |
       make ${{ parameters.testCommand }}
-        test_result=$?
-        if [ "$test_result" == "0" ]
+      test_result=$?
+      if [ "$test_result" == "0" ]
+      then
+        if [ -f $testResultFile ]
         then
-          if [ -f $testResultFile ]
+          seedvalue=$(grep -Pio 'name="seed" value="\d+"' $testResultFile)
+          echo "##[command]$seedvalue"
+          if [ $(grep "^<testsuite name=\"rspec\"" $testResultFile | cut -d' ' -f5 | cut -d'"' -f2) -gt 0 ]
           then
-            if [ $(grep "^<testsuite name=\"rspec\"" $testResultFile | cut -d' ' -f5 | cut -d'"' -f2) -gt 0 ]
-            then
-              echo "##vso[task.logissue type=error]One or more rspec tests failed"
-              exit 1
-            fi
-            if [ $(grep "^<testsuite name=\"rspec\"" $testResultFile | cut -d' ' -f4 | cut -d'"' -f2) -gt 0 ]
-            then
-              echo "##vso[task.logissue type=warning]One or more rspec tests were skipped"
-            fi
-          else
-            echo "##vso[task.logissue type=error]rspec-results file not found."
+            echo "##vso[task.logissue type=error]One or more rspec tests failed"
             exit 1
           fi
-          exit 0
+          if [ $(grep "^<testsuite name=\"rspec\"" $testResultFile | cut -d' ' -f4 | cut -d'"' -f2) -gt 0 ]
+          then
+            echo "##vso[task.logissue type=warning]One or more rspec tests were skipped"
+          fi
         else
-          echo "##vso[task.logissue type=error]Rspec test task exited abnormally."
+          echo "##vso[task.logissue type=error]rspec-results file not found."
           exit 1
         fi
+        exit 0
+      else
+        echo "##vso[task.logissue type=error]Rspec test task exited abnormally."
+        exit 1
+      fi
     displayName: 'Execute ${{ parameters.testCommand }}'
     env:
       testResultFile: ${{ parameters.testResultsFile }}
